qbcore-framework/qb-multicharacter

html/script.js
Check for white spaces, empty and sanitize input
=> Check for empty spaces

html/script.js
[#15 ](https://github.com/qbcore-framework/qb-multicharacter/issues/15)
=> fixed Return Button does not work

server/main.lua
When creating a character you are set to a random bucket. You will be returned when leaving your apartment.
=> Enter random bucket when creating char

client/main.lua
Using the config.lua CamCoords in the actual cam creation.
no
- yes
- yes
- yes
=> Config.CamCoords

config.lua
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality?
yes
- Does your code fit the style guidelines?
yes
- Does your PR fit the contribution guidelines?
yes
=> fix(config.lua): correct cam coords

html/style.css
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] 
- Does your code fit the style guidelines? [yes] 
- Does your PR fit the contribution guidelines? [yes]
=> update forget font

server/main.lua
**Makes it so join logs now contains licenses, ips and discord identifiers.**
If your PR is to fix an issue mention that issue here: **N/A**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? **Yes**
- Does your code fit the style guidelines? **Yes**
- Does your PR fit the contribution guidelines? **Yes**
=> Better join logs

client/main.lua
Default Ped Fix, Deletes after character is loaded
=> Default Ped

html/style.css
- Fix CSS Janky Alignments
- Add cursor: pointer to buttons
=> Fix CSS Jank & Buttons

html/script.js
I have added another reset in the **resetAll** function. This edit may prevent bugs that can occur, it is safer to have the reset there.
- Sometimes after using /logout command you would not be able to select a character.
- Have you personally loaded this code into an updated qbcore project and checked all its functionality? yes (Running on my production server)
=> Reset selectedChar

server/main.lua
Huge performance improvement for large servers. When having 100+ players and a lot of houses, this was hitching the server and causing everyone to timeout and required a server restart. This fixes that issue completely.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest) yes
- Does your code fit the style guidelines? [yes/no] yes
- Does your PR fit the contribution guidelines? [yes/no] yes
=> improvement(server): Huge performance improvement for large servers

client/main.lua, html/index.html, html/script.js, html/style.css
In a previous [PR](https://github.com/qbcore-framework/qb-multicharacter/pull/91) it was noted that the character registration form would not pass validation if there were spaces in the Nationality field and a function was added to remove whitespace as a workaround. This PR removes that function and fixes the validation logic to allow whitespace in the Firstname, Lastname and Nationality fields.
Additionally, there was no error-catching other than a printed statement to console. A new UI function and corresponding HTML and CSS have been added to give the user error feedback on form validation failure.
Finally, the material icon link and CSS were broken, these have been updated.
- Have you personally …
=> Form validation fix and error feedback UI added. Fixes #117

html/style.css
Add hover effect on characters & transition
=> Add hover effect on characters & transition

html/script.js, html/style.css
add job grade according to job and update previous <div> with current <span>
=> add grade to job

html/script.js, html/style.css
Keeps the buttons visible and only scrolls the characters
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]
=> Tidier scrolling with large number of characters

server/main.lua
=> deleted character confirming

.github/workflows/lint.yml
Added qbapartments to allow use of globals
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [no] (Be honest)
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]
=> [lint] Add qbapartments to extra_libs

client/main.lua
- Replace gethashkey with joaat 
- Add DeletePed native to resolve the issue where the chosen deleted character's ped still remains after being deleted.
=> small tweaks

html/index.html
This fixes the issue where the gender text says "1 / 0" instead of Male or Female.
Yes
Yes
Yes
=> Quick fix for gender label

client/main.lua, fxmanifest.lua, html/index.html, html/style.css, locales/en.lua, locales/sv.lua, server/main.lua
This PR adds translations to the multicharacter system and also resolves issue #147 & #148.
Yeah, issue #147 & #148
Yes
Yes
Yes
=> Add translations + Fix the open issues + Fix UI Responsiveness

locales/es.lua
=> add translation to spanish

fxmanifest.lua, locales/ar.lua, locales/en.lua, locales/es.lua, locales/fr.lua, locales/it.lua, locales/sv.lua
adding auto switch locale system
=> auto switch locale system

locales/ar.lua, locales/en.lua, locales/es.lua, locales/fr.lua, locales/it.lua, locales/sv.lua
Lazy fix for UI translations not working after #160.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? **yes**
- Does your code fit the style guidelines? **yes**
- Does your PR fit the contribution guidelines? **yes**
=> Fix UI translations not working

client/main.lua, html/index.html, locales/ar.lua, locales/en.lua, locales/es.lua, locales/fr.lua, locales/it.lua, locales/sv.lua
#164 provided a lazy fix for Locales in the UI, so properly implement them for translation fallbacks to work.
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? **no**
- Does your code fit the style guidelines? **yes**
- Does your PR fit the contribution guidelines? **yes**
=> Properly implement UI locales

html/index.html
This seems to resolve the #173 issue. Not very experienced with Vue though, needs some double checking.
=> Cannot access viewmodel fix

html/index.html
Axios
v.1.1.3
this needs tested
=> axios update (needs test)

client/main.lua, config.lua, html/index.html, html/style.css
Country list fetch
Config option **customNationality**
- If it's  true, the field will be a text input.
- If it's false, the field will be select with a dropdown of the countris list.
=> Add country list input feature

locales/vi.lua
=> [TRANSLATIONS] Vietnamese

locales/cs.lua
- Does your PR fit the contribution guidelines? yes/
=> add cs translate

locales/ja.lua
Yes, I tried it my local server and successfully worked.
Yes
Yes
=> Added Japanese locales

locales/fi.lua
=> [TRANSLATIONS] Finnish

client/main.lua
This push will save database fetch every time a character is clicked on, it will only fetch data once and save the player model and data in memory as it is useless to grab the same data that is already present on the client.
Also created a function to load the model as the same code is called 3 times
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? Yes, I have tested it every step up the way 
- Does your code fit the style guidelines? Yes
- Does your PR fit the contribution guidelines? Yes
=> optimize+clean(Character Selector):Spam Prevention + Code Cleanup

locales/ja.lua
This PR fixes a simple code error in the Japanese localization file
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes]
- Does your code fit the style guidelines? [yes]
- Does your PR fit the contribution guidelines? [yes]
=> Fix japanese localization file

server/main.lua
**Questions:**
This is one of three pull requests across three resources to address this issue
Other PRs:
https://github.com/qbcore-framework/qb-apartments/pull/127
https://github.com/qbcore-framework/qb-spawn/pull/81
=> Fix apartments.starting related bug
